export const actionTypes = {
    FETCH_PRODUCTS: "FETCH_PRODUCTS",
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
}

export const SET_USER = "SET_USER";
export const SET_SHOPPING_CART = "SET_SHOPPING_CART";
export const LOGOUT_USER = "LOGOUT_USER";
export const REMOTE_PRODUCT_CART = "REMOTE_PRODUCT_CART";